import assert from 'node:assert/strict';
import type { Advisor, Card, GameEvent, GameState } from '../src/game/types';
import {
  MANUAL_SAVE_SLOT_COUNT,
  clearManualSaveSlot,
  deserializeGameState,
  readSaveLibrary,
  renameManualSaveSlot,
  serializeGameState,
  writeAutosave,
  writeManualSave,
} from '../src/game/saveGame';
import { addEasyUndoOption } from '../src/game/easyMode';

class MemoryStorage implements Storage {
  private readonly values = new Map<string, string>();

  get length() { return this.values.size; }
  clear() { this.values.clear(); }
  getItem(key: string) { return this.values.get(key) ?? null; }
  key(index: number) { return [...this.values.keys()][index] ?? null; }
  removeItem(key: string) { this.values.delete(key); }
  setItem(key: string, value: string) { this.values.set(key, value); }
}

Object.defineProperty(globalThis, 'localStorage', { value: new MemoryStorage(), configurable: true });
Object.defineProperty(globalThis, 'window', {
  value: { dispatchEvent: () => true },
  configurable: true,
});
if (typeof globalThis.CustomEvent === 'undefined') {
  Object.defineProperty(globalThis, 'CustomEvent', {
    value: class CustomEvent {
      constructor(public type: string) {}
    },
    configurable: true,
  });
}

const nestedEvent: GameEvent = {
  id: 'save_test_nested',
  title: 'Nested report',
  description: 'A dynamically generated report.',
  options: [{
    text: 'Accept report',
    effect: (state) => ({ resources: state.resources + 7, currentEvent: null }),
  }],
};

const rootEvent: GameEvent = {
  id: 'save_test_root',
  title: 'Root decision',
  description: 'A root generated by a card.',
  options: [{
    text: 'Open report',
    effect: () => ({ currentEvent: nestedEvent }),
  }],
};

const card: Card = {
  id: 'save_test_card',
  title: 'Save Test Card',
  type: 'Action',
  description: 'Test only.',
  cost: 1,
  effect: () => ({ currentEvent: rootEvent }),
};

const advisor: Advisor = {
  id: 'save_test_advisor',
  name: 'Save Test Advisor',
  faction: 'None',
  description: 'Test only.',
  actions: [{
    id: 'save_test_action',
    title: 'Test',
    subtitle: 'Test',
    description: 'Test only.',
    condition: () => true,
    effect: () => ({ resources: 99 }),
  }],
};

const state = {
  screen: 'game',
  scenario: '1931',
  difficulty: 'normal',
  year: 1932,
  month: 4,
  phase: 'event',
  language: 'zh',
  resources: 3,
  hand: [card],
  actionDeck: [],
  governmentDeck: [],
  militaryDeck: [],
  discard: [],
  activeAdvisors: [advisor, null, null],
  advisorPool: [],
  pendingEvents: [rootEvent],
  currentEvent: nestedEvent,
} as unknown as GameState;

const snapshot = serializeGameState(state);
const serializedText = JSON.stringify(snapshot);
assert.equal(snapshot.runtime.hand[0], card.id);
assert.equal(snapshot.runtime.activeAdvisors[0], advisor.id);
assert.equal(snapshot.runtime.currentEvent?.id, nestedEvent.id);
assert.equal(serializedText.includes('Accept report'), true);
assert.equal(serializedText.includes('=>'), false, 'Function source must not leak into serialized saves.');

const restored = deserializeGameState(JSON.parse(serializedText), {
  cards: [card],
  advisors: [advisor],
  events: [],
});
assert.equal(restored.hand[0], card);
assert.equal(restored.activeAdvisors[0], advisor);
assert.equal(typeof restored.currentEvent?.options[0].effect, 'function');
assert.equal(restored.currentEvent?.options[0].effect(restored).resources, 10);

const easyStateBeforeCard = {
  ...state,
  difficulty: 'easy',
  resources: 8,
  currentEvent: null,
  pendingEvents: [],
  easyUndoState: null,
} as GameState;
const easyStateDuringCard = {
  ...state,
  difficulty: 'easy',
  resources: 3,
  currentEvent: addEasyUndoOption(rootEvent),
  pendingEvents: [],
  easyUndoState: easyStateBeforeCard,
} as GameState;
const restoredEasyState = deserializeGameState(serializeGameState(easyStateDuringCard), {
  cards: [card],
  advisors: [advisor],
  events: [],
});
assert.equal(restoredEasyState.currentEvent?.options.length, 2);
const refundResult = restoredEasyState.currentEvent?.options[1].effect(restoredEasyState);
assert.equal(refundResult?.resources, 8, 'Easy-mode refunds must survive a save/load round trip.');
assert.equal(refundResult?.easyUndoState, null);

let library = readSaveLibrary();
assert.equal(library.manualSlots.length, MANUAL_SAVE_SLOT_COUNT);
assert.equal(library.autosave, null);

library = writeAutosave(state);
assert.equal(library.autosave?.summary.year, 1932);

library = renameManualSaveSlot('manual-1', 'Barcelona Campaign');
assert.equal(library.manualSlots[0].name, 'Barcelona Campaign');

library = writeManualSave('manual-1', state);
assert.equal(library.manualSlots[0].record?.snapshot.runtime.currentEvent?.id, nestedEvent.id);

library = clearManualSaveSlot('manual-1');
assert.equal(library.manualSlots[0].record, null);
assert.equal(library.manualSlots[0].name, 'Barcelona Campaign', 'Clearing a save must preserve its renamed slot name.');

console.log('Save-system serialization, dynamic-event hydration, autosave, and slot tests passed.');
