import assert from 'node:assert/strict';
import type { Advisor, Card, GameEvent, GameState } from '../src/game/types';
import { MapFaction } from '../src/map/types_map';
import {
  MANUAL_SAVE_SLOT_COUNT,
  clearManualSaveSlot,
  deserializeGameState,
  readSaveLibrary,
  renameManualSaveSlot,
  serializeGameState,
  writeAutosave,
  writeManualSave,
} from '../src/game/saveGame';
import { addEasyUndoOption } from '../src/game/easyMode';

class MemoryStorage implements Storage {
  private readonly values = new Map<string, string>();

  get length() { return this.values.size; }
  clear() { this.values.clear(); }
  getItem(key: string) { return this.values.get(key) ?? null; }
  key(index: number) { return [...this.values.keys()][index] ?? null; }
  removeItem(key: string) { this.values.delete(key); }
  setItem(key: string, value: string) { this.values.set(key, value); }
}

Object.defineProperty(globalThis, 'localStorage', { value: new MemoryStorage(), configurable: true });
Object.defineProperty(globalThis, 'window', {
  value: { dispatchEvent: () => true },
  configurable: true,
});
if (typeof globalThis.CustomEvent === 'undefined') {
  Object.defineProperty(globalThis, 'CustomEvent', {
    value: class CustomEvent {
      constructor(public type: string) {}
    },
    configurable: true,
  });
}

const nestedEvent: GameEvent = {
  id: 'save_test_nested',
  title: 'Nested report',
  description: 'A dynamically generated report.',
  options: [{
    text: 'Accept report',
    effect: (state) => ({ resources: state.resources + 7, currentEvent: null }),
  }],
};

const rootEvent: GameEvent = {
  id: 'save_test_root',
  title: 'Root decision',
  description: 'A root generated by a card.',
  options: [{
    text: 'Open report',
    effect: () => ({ currentEvent: nestedEvent }),
  }],
};

const card: Card = {
  id: 'save_test_card',
  title: 'Save Test Card',
  type: 'Action',
  description: 'Test only.',
  cost: 1,
  effect: () => ({ currentEvent: rootEvent }),
};

const advisor: Advisor = {
  id: 'save_test_advisor',
  name: 'Save Test Advisor',
  faction: 'None',
  description: 'Test only.',
  actions: [{
    id: 'save_test_action',
    title: 'Test',
    subtitle: 'Test',
    description: 'Test only.',
    condition: () => true,
    effect: () => ({ resources: 99 }),
  }],
};

const legacyArmy = {
  id: 'legacy_army',
  faction: MapFaction.REPUBLICAN,
  provinceId: 'madrid',
  movesLeft: 2,
  manpower: 1000,
  maxManpower: 1000,
  composition: { infantry: 1000, artillery: 0, tanks: 0 },
  designedComposition: { infantry: 1000, artillery: 0, tanks: 0 },
  morale: 50,
  militarization: 10,
};

const state = {
  screen: 'game',
  scenario: '1931',
  difficulty: 'normal',
  year: 1932,
  month: 4,
  phase: 'event',
  language: 'zh',
  resources: 3,
  hand: [card],
  actionDeck: [],
  governmentDeck: [],
  militaryDeck: [],
  discard: [],
  activeAdvisors: [advisor, null, null],
  advisorPool: [],
  pendingEvents: [rootEvent],
  currentEvent: nestedEvent,
  armies: [legacyArmy],
} as unknown as GameState;

const snapshot = serializeGameState(state);
const serializedText = JSON.stringify(snapshot);
assert.equal(snapshot.runtime.hand[0], card.id);
assert.equal(snapshot.runtime.activeAdvisors[0], advisor.id);
assert.equal(snapshot.runtime.currentEvent?.id, nestedEvent.id);
assert.equal(serializedText.includes('Accept report'), true);
assert.equal(serializedText.includes('=>'), false, 'Function source must not leak into serialized saves.');

const restored = deserializeGameState(JSON.parse(serializedText), {
  cards: [card],
  advisors: [advisor],
  events: [],
});
assert.equal(restored.hand[0], card);
assert.equal(restored.activeAdvisors[0], advisor);
assert.equal(restored.armies?.[0]?.identity, 'gov', 'Legacy armies must receive the default gov identity.');
assert.equal(restored.mapCurrentPlayer, MapFaction.REPUBLICAN, 'Legacy saves must receive the default map player.');
assert.equal(restored.mapSelectedProvinceId, null);
assert.deepEqual(restored.mapSelectedArmyIds, []);
assert(Object.keys(restored.provinces).length > 0, 'Legacy saves must receive the canonical province map.');
assert.equal(restored.mapResources[MapFaction.WORKERS_ALLIANCE].manpower, 0, 'Every map faction must have normalized resources.');
assert.equal(typeof restored.currentEvent?.options[0].effect, 'function');
assert.equal(restored.currentEvent?.options[0].effect(restored).resources, 10);

const legacyOrganizationSnapshot = JSON.parse(serializedText);
legacyOrganizationSnapshot.state.civilWarStatus = 'not_started';
legacyOrganizationSnapshot.state.uhp_journal_activated = true;
Object.assign(legacyOrganizationSnapshot.state, {
  socialism: 12,
  nationalism: 34,
  pacifism: 56,
  democratization: 78,
  pro_republic: 90,
});
legacyOrganizationSnapshot.state.journal = {
  journal_uhp: { id: 'journal_uhp', status: 'inactive', progress: 0 },
};
legacyOrganizationSnapshot.state.organizations = {
  UR: { established: true, status: 'active' },
  MC: { established: true, status: 'active', militiaManpower: 450 },
};
legacyOrganizationSnapshot.state.armedForces = {
  militias: { cntFai: 200, maoc: 80 },
  entityPools: {
    milicias_confederales: {
      entityId: 'milicias_confederales',
      organizationId: 'MC',
      owner: 'CNT_FAI',
      status: 'active',
      manpower: 100,
      artillery: 2,
      tanks: 1,
    },
  },
};
const restoredLegacyOrganizations = deserializeGameState(legacyOrganizationSnapshot, {
  cards: [card],
  advisors: [advisor],
  events: [],
});
assert.equal(restoredLegacyOrganizations.organizations.UNIO_RABASSAIRES?.established, true, 'The legacy UR union entry must move to its canonical id.');
assert.equal(restoredLegacyOrganizations.organizations.UR?.established, false, 'The UR party must remain a separate canonical organization.');
assert.equal(restoredLegacyOrganizations.organizations.DC?.established, true, 'The legacy MC organization must move to DC.');
assert.equal(restoredLegacyOrganizations.armedForces.entityPools.cnt_defense_committees.manpower, 450, 'Organization manpower must migrate to the canonical entity pool without double counting.');
assert.equal(restoredLegacyOrganizations.armedForces.entityPools.cnt_defense_committees.artillery, 2);
assert.equal(restoredLegacyOrganizations.armedForces.entityPools.maoc.manpower, 80);
assert.equal(restoredLegacyOrganizations.journal.journal_uhp.status, 'active');
assert.equal('uhp_journal_activated' in restoredLegacyOrganizations, false);
assert.equal('militias' in restoredLegacyOrganizations.armedForces, false);
assert.equal('militiaManpower' in restoredLegacyOrganizations.organizations.DC, false);
for (const key of ['socialism', 'nationalism', 'pacifism', 'democratization', 'pro_republic']) {
  assert.equal(key in restoredLegacyOrganizations, false, `Legacy SDAAH field ${key} must be removed during load.`);
}

const partialMapSnapshot = JSON.parse(serializedText);
partialMapSnapshot.state.mapResources = { [MapFaction.REPUBLICAN]: { manpower: 321 } };
const restoredPartialMap = deserializeGameState(partialMapSnapshot, {
  cards: [card],
  advisors: [advisor],
  events: [],
});
assert.equal(restoredPartialMap.mapResources[MapFaction.REPUBLICAN].manpower, 321);
assert.equal(restoredPartialMap.mapResources[MapFaction.REPUBLICAN].supplies, 8000, 'Partial resource records must merge with canonical defaults.');
assert.equal(restoredPartialMap.mapResources[MapFaction.NATIONALIST].manpower, 12000, 'Missing factions must be restored from canonical defaults.');

const easyStateBeforeCard = {
  ...state,
  difficulty: 'easy',
  resources: 8,
  currentEvent: null,
  pendingEvents: [],
  easyUndoState: null,
} as GameState;
const easyStateDuringCard = {
  ...state,
  difficulty: 'easy',
  resources: 3,
  currentEvent: addEasyUndoOption(rootEvent),
  pendingEvents: [],
  easyUndoState: easyStateBeforeCard,
} as GameState;
const restoredEasyState = deserializeGameState(serializeGameState(easyStateDuringCard), {
  cards: [card],
  advisors: [advisor],
  events: [],
});
assert.equal(restoredEasyState.currentEvent?.options.length, 2);
const refundResult = restoredEasyState.currentEvent?.options[1].effect(restoredEasyState);
assert.equal(refundResult?.resources, 8, 'Easy-mode refunds must survive a save/load round trip.');
assert.equal(refundResult?.easyUndoState, null);

let library = readSaveLibrary();
assert.equal(library.manualSlots.length, MANUAL_SAVE_SLOT_COUNT);
assert.equal(library.autosave, null);

library = writeAutosave(state);
assert.equal(library.autosave?.summary.year, 1932);

library = renameManualSaveSlot('manual-1', 'Barcelona Campaign');
assert.equal(library.manualSlots[0].name, 'Barcelona Campaign');

library = writeManualSave('manual-1', state);
assert.equal(library.manualSlots[0].record?.snapshot.runtime.currentEvent?.id, nestedEvent.id);

library = clearManualSaveSlot('manual-1');
assert.equal(library.manualSlots[0].record, null);
assert.equal(library.manualSlots[0].name, 'Barcelona Campaign', 'Clearing a save must preserve its renamed slot name.');

console.log('Save-system serialization, dynamic-event hydration, autosave, and slot tests passed.');
